site: Atomic Thoughts
url: https://a-t.netlify.app
title: Atomic Thoughts

author:
  twitter: #yourusername
  name: Ankit
  avatar:
  email: #youremail
  url: www.sudoankit.xyz
  
permalink: pretty

baseurl: ""

highlighter: rogue

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"